name = "smartmetal"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
VITE_API_BASE_URL = "https://smartmetal-backend-293567440480.us-central1.run.app/api"

[env.production]
name = "smartmetal"

[env.production.vars]
VITE_API_BASE_URL = "https://smartmetal-backend-293567440480.us-central1.run.app/api"

[env.preview]
name = "smartmetal-preview"

[env.preview.vars]
VITE_API_BASE_URL = "https://smartmetal-backend-293567440480.us-central1.run.app/api"

